name: deeplink_x_platform_interface
description: "A common platform interface for the deeplink_x plugin."
version: 0.0.3

repository: https://github.com/DeeplinkX/DeeplinkXPlatformInterface

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
